#Spring properties
spring: 
  aop:
    auto: true
    proxy-target-class: false
  messages: 
    always-use-message-format: false

    basename:  messages
    cache-seconds: -1
  mvc:
    dispatch-trace-request: false
    dispatch-options-request: true
  couchbase:
    bucket:
      name: default
      
thymeleaf:
    cache: true
    
    
 #Security properties
security:
  oauth2:
    resource:
      prefer-token-info: true
      
      service-id: resource


banner:
  location: classpath:/folderBanner/banner.txt
  
  
server:
  error:
    whitelabel:
      enabled: false
      

  
    
    